services:
  - type: web
    name: y2mate-backend
    env: python
    plan: starter
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.download_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
